---
title: "my-website"
author: "Kavi Haria Shah"
date: 2025-01-15
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

## Overview 

This course is designed to equip all members of the Part III Systems Biology cohort at the University of Cambridge with a foundational understanding of Python. This will be utilised in various subsequent sections of the programme. While no prior knowledge of Python is required, basic familiarity with coding is assumed. Additionally, this course may serve as a valuable introduction for those interested in learning Python for data science, particularly for those working with biological data. 

::: {.callout-tip}
### Aims

- My aims are to...
:::


### Target Audience

### Prerequisites

- Have some prior experience in coding, whether in Python or another programming language.

<!-- Training Developer note: comment the following section out if you did not assign levels to your exercises -->
### Exercises


## Citation

